version: '3.8'

services:
  postgres:
    container_name: animalshop_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: abcdefgh
      POSTGRES_DB: animalshop_db
      PGDATA: /data/postgres
    volumes:
      - animalshop-postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: always

  pgadmin:
    container_name: animalshop_pgadmin_container
    image: postgres
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: changeme
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - animalshop-pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
  animalshop-postgres:
  animalshop-pgadmin:

